FROM epinux/pygeoapi:latest

LABEL maintainer="Massimo Di Stefano <massimods@met.no>"

RUN apt-get update && apt-get dist-upgrade -y

RUN apt-get install -y celery python3-mapscript python3-satpy python3-celery python3-h5netcdf python3-netcdf4

RUN apt-get install -y python3-redis python3-rediscluster python3-redisearch-py python3-rq

# RUN apt-get install -y git
# RUN pip install git+https://github.com/epifanio/satpy-pygeoapi-plugin

COPY ./ /satpy/

RUN pip install -e /satpy/

ENV PYGEOAPI_OPENAPI=example-openapi.yml 

ENV PYGEOAPI_CONFIG=/satpy/etc/example-config.yml  

# COPY docker/pygeoapi-config.yml /pygeoapi/example-config.yml

# ENV PYGEOAPI_CONFIG=/pygeoapi/example-config.yml

EXPOSE 80
EXPOSE 5000

COPY docker/start_pygeoapi.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]