# =================================================================
#
# Authors: Tom Kralidis <tomkralidis@gmail.com>
#
# Copyright (c) 2020 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
    bind:
        host: 0.0.0.0
        port: 80
    url: http://0.0.0.0
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        # First language is the default language
        - en-US
        - fr-CA
    # cors: true
    pretty_print: true
    limit: 10
    # templates:
    # path: /path/to/Jinja2/templates
    # static: /path/to/static/folder # css/js/img
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    manager:
        name: satpy_pygeoapi_plugin.celery_redis_manager.celery_redis_manager
        broker: redis://
        backend: redis://
        result_backend: redis://
    # manager:
    #     name: TinyDB
    #     connection: /tmp/pygeoapi-process-manager.db
    #     output_dir: /tmp/
    # ogc_schemas_location: /opt/schemas.opengis.net

logging:
    level: DEBUG
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title:
            en: pygeoapi default instance
            fr: instance par défaut de pygeoapi
        description:
            en: pygeoapi provides an API to geospatial data
            fr: pygeoapi fournit une API aux données géospatiales
        keywords:
            en:
                - geospatial
                - data
                - api
            fr:
                - géospatiale
                - données
                - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Organization Name
        url: https://pygeoapi.io
    contact:
        name: Lastname, Firstname
        position: Position Title
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Country
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: you@example.org
        url: Contact URL
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

resources:
    hello-world:
        type: process
        processor:
            name: HelloWorld

    mapserver_metno:
        type: collection
        title: MapServer demo METNO
        description: MapServer demo METNO
        keywords:
            - MapServer
            - S-ENDA
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://mapserver-dev.mapserver.k8s.met.no/okd-satellite
              hreflang: en-US
        extents:
            spatial:
                bbox: [-30, 40, 30, 70]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                #datetime: 2023-01-11T06:34:20Z
                begin: 2023-01-11T06:34:20Z
                end: 2023-01-21T06:34:20Z
        providers:
            - type: map
              name: WMSFacade
              data: https://mapserver-dev.mapserver.k8s.met.no/okd-satellite
              options:
                  #datetime: 2023-01-11T06:34:20Z
                  layer: overview_with_night_ir_polar
                  style: default
              format:
                  name: png
                  mimetype: image/png

    process-netcdf:
        type: process
        processor:
            name: satpy_pygeoapi_plugin.process_netcdf.ProcessNetcdfProcessor
